import styles from '../styles/Home.module.css';
import Widget from '../component/Widget';
import Feeds from '../component/Feeds';
import Sidebar from '../component/Sidebar';
import {useSession , SessionProvider } from 'next-auth/react'
import Link from 'next/link';
import Comment from '../component/Comment';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

export default function Index({feeds , News , users }) {
  const {data:session} = useSession();
  const [x , setX] = useState(1)
  const router = useRouter();
  useEffect(() => {
    setTimeout(() => {
      setX(x+1)
    }, 2000);
    
  }, []);

  useEffect(() => {
    if(x > 1 && !session)
    router.push('/signin')
  }, [x]);
  console.log(session)
  if(session){
 
  return (
    <SessionProvider>
    < >
      <Head>
        <title>Twitter page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
        <div  >
          <div className={styles.container}>
          <div ><Sidebar /></div> 
          <div ><Feeds feeds={feeds.articles} /></div>
          <div className={styles.Widget}><Widget articles={News.articles} profiles={users?.users} /></div>
          <Comment />
          </div>
      </div>
      
    </>
    </SessionProvider>
  )
}
}
export async function getServerSideProps(){
  const feeds = await fetch("https://saurav.tech/NewsAPI/top-headlines/category/health/in.json").then(res => res.json())
  const News = await fetch("https://saurav.tech/NewsAPI/everything/cnn.json").then(res => res.json())
  const users = await fetch("https://dummyjson.com/users").then(res => res.json())
  return({
    props:{
      feeds : feeds,
      News : News,
      users: users,
    }
  })
}
